services:
  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
      - "9093:9093"

  kafka-init:
    image: confluentinc/cp-kafka:8.1.0
    depends_on:
      - kafka
    entrypoint: >
      bash -c "
        until kafka-topics --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
          sleep 1
        done &&
        kafka-topics --create --if-not-exists --topic signups_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic activity_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic support_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic billing_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
      "
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: churn_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d churn_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/etc/grafana/dashboards

  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      BACKEND_STORE_URI: postgresql://admin:admin@postgres:5432/mlflow_db
      ARTIFACT_ROOT: /mlruns
    volumes:
      - ./mlruns:/mlruns
      - ./ml:/app/ml
    working_dir: /app/ml
    command: >
      bash -c "
      pip install mlflow[extras] psycopg2-binary &&
      export MLFLOW_TRACKING_URI=http://0.0.0.0:5000 &&
      mlflow server --backend-store-uri postgresql://admin:admin@postgres:5432/mlflow_db --default-artifact-root /mlruns --host 0.0.0.0 --port 5000
      "
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  airflow:
    image: apache/airflow:2.8.0
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
      _PIP_ADDITIONAL_REQUIREMENTS: "psycopg2-binary==2.9.6 mlflow==2.5.0 pandas==2.2.3 scikit-learn==1.3.2"
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./ml:/opt/airflow/ml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mlflow
    entrypoint: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true &&
      airflow scheduler & airflow webserver
      "