apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: churn_db
    user: admin
    password: admin
    jsonData:
      sslmode: "disable"