{
 "title": "Churn analytics",
 "time": { "from": "2025-01-01T00:00:00.000Z", "to": "2025-01-08T00:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Churn rate over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT signup_day AS \"time\", churn_rate FROM churn_summary;"
    }
   ]
  },
  {
   "title": "Avg revenue before churn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(AVG(total_spent)::numeric, 2) FROM churned_billing_summary;"
    }
   ]
  },
  {
   "title": "Avg tickets before churn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(AVG(total_tickets)::numeric, 2) FROM churned_support_summary;"
    }
   ]
  },
  {
   "title": "Churn by region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT region, COUNT(*) FROM churn_insights GROUP BY region;"
    }
   ]
  }
 ]
}