{
 "title": "User Growth & Engagement",
 "time": { "from": "2025-01-01T00:00:00.000Z", "to": "2025-01-23T00:00:00.000Z" },
 "panels": [
  {
   "title": "Average session lenght per plan",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT plan, avg_session_length FROM avg_session_length_per_plan;"
    }
   ]
  },
  {
   "title": "Plan Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT plan AS \"Plan\", count AS \"Users\" FROM plan_distribution_summary;"
    }
   ]
  },
  {
   "title": "Daily Signups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT day, total_signups FROM daily_signups_summary ORDER BY day;"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT day AS \"time\", active_users FROM daily_active_users ORDER BY day;"
    }
   ]
  },
  {
   "title": "Signups by Region and Device",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT region, device, count FROM signups_by_region_device;"
    }
   ]
  }
 ]
}