apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: churn_db
    user: admin
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    secureJsonData:
      password: admin
    isDefault: true
    editable: false